-- AlterTable: Add new fields to banners table
ALTER TABLE "banners" ADD COLUMN IF NOT EXISTS "topTitle" TEXT;
ALTER TABLE "banners" ADD COLUMN IF NOT EXISTS "discount" TEXT;
ALTER TABLE "banners" ADD COLUMN IF NOT EXISTS "imageWidth" INTEGER DEFAULT 1200;
ALTER TABLE "banners" ADD COLUMN IF NOT EXISTS "imageHeight" INTEGER DEFAULT 600;
ALTER TABLE "banners" ADD COLUMN IF NOT EXISTS "isCarousel" BOOLEAN DEFAULT false;
ALTER TABLE "banners" ADD COLUMN IF NOT EXISTS "buttonColor" TEXT DEFAULT '#3B82F6';
ALTER TABLE "banners" ADD COLUMN IF NOT EXISTS "buttonTextColor" TEXT DEFAULT '#FFFFFF';

