-- AlterTable
ALTER TABLE "banners" ADD COLUMN IF NOT EXISTS "bannerColor" TEXT DEFAULT '#FFFFFF';
ALTER TABLE "banners" ADD COLUMN IF NOT EXISTS "titleColor" TEXT DEFAULT '#000000';
ALTER TABLE "banners" ADD COLUMN IF NOT EXISTS "descriptionColor" TEXT DEFAULT '#666666';

